
version: 2

models:
  - name: dbt_companies
    description: "company model"
    columns:
      - name: id
        description: "The primary key for this table"
      - name: name
        description: "Company name"
        tests:
          - unique
          - not_null

  - name: dbt_companies_view
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: tenants
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
